name: Terraform

on:
  push:
    branches:
      - main
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Create SSH Key File
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.YOGI_EC2_KEY }}" > /home/runner/.ssh/mySAKey.pem
          chmod 600 /home/runner/.ssh/mySAKey.pem
          ls -al /home/runner/.ssh  # Verify permissions and existence
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform  # Update this path if necessary

      - name: Plan Terraform Destroy
        run: terraform plan -destroy -out=destroy.plan
        working-directory: /usr/src/app/my-strapi-app  # Update this path if necessary

      - name: Apply Terraform Destroy
        run: terraform apply -auto-approve destroy.plan
        working-directory: /usr/src/app/my-strapi-app

      - name: Plan Terraform Apply
        run: terraform plan -out=apply.plan
        working-directory: /usr/src/app/my-strapi-app

        
      - name: Apply Terraform
        run: terraform apply -auto-approve -var="private_key_path=/home/runner/.ssh/mySAKey.pem"
        working-directory: ./terraform  # Update this path if necessary
